name: flutter_board
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  freezed_annotation: ^1.1.0
  provider: ^6.0.2
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.8

flutter:

  uses-material-design: true
